### ISSUE TITLE
Broken comparison function in compute_suggestion

### ISSUE THREAD

**Issue by ghost** [alopatindev/iwls#1]
[This](https://github.com/alopatindev/iwls/blob/7316d2125f848914e90b26d532dc2165db4054bf/src/lib.rs#L224) comparison function is broken.

According to it, these two statements are true at the same time:
* `(11, 0.0) < (14, 0.0)`
* `(14, 0.0) < (11, 0.0)`

The vector will be sorted in a totally unreliable order.
See this issue and the fix suggested by @bluss: rust-lang/rust#38685

**Comment by alopatindev** [comment]
Thank you for finding this! Fixed.

**Comment by stjepang** [comment]
Glad this got fixed! Just a quick note - you can simplify `compare_channels_load` a bit... :)

```rust
fn compare_channels_load(a: &ChannelLoad, b: &ChannelLoad) -> cmp::Ordering {
    (&a.1, &a.0).partial_cmp(&(&b.1, &b.0)).unwrap()
}
```
